server:
  port: 9092
  host: localhost

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

  
spring:
  application:
    name: NS-USER-SERVICE
  
zipkin:
  baseUrl: http://127.0.0.1:9411/

